name: CI and build docker image

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]
  workflow_dispatch:
   inputs:
    version:
      description: "image tag som släpps till produktion"
      required: true

jobs:
  test_and_build:
    runs-on: ubuntu-latest

    steps:
      - name: check out code
        uses: actions/checkout@v4

      - name: set up javen enviroment
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "maven"

      - name: build and run tests
        run: mvn -B package

      - name: Log in to docker hub
        if: github.event_name == 'push'
        run: echo ${{secrets.DOCKERHUB_TOKEN}} | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin

      - name: build image
        run: |
          docker build -t craty321/booking-service-java25:${{github.run_number}} .

      - name: push docker hub
        if: github.event_name == 'push'
        run: |
          docker push craty321/booking-service-java25:${{github.run_number}}
  deploy_staging:
    if: github.event_name == 'push'
    needs: test_and_build
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - run: |
         docker buildx imagetools create \
         -t craty321/booking-service-java25:staging \
         craty321/booking-service-java25:${{ github.run_number }}

  deploy_production:
   if: github.event_name == 'workflow_dispatch'
   runs-on: ubuntu-latest
   environment: production
   steps:
       - run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
       - run: |
          docker buildx imagetools create \
          -t craty321/booking-service-java25:production \
          craty321/booking-service-java25:${{ inputs.version }}
